### ISSUE TITLE
可以看这个帖子, 我写过一个简单的雏形

### ISSUE THREAD

**Issue by oeyoews** [tiddly-gittly/drive#2]
https://talk.tiddlywiki.org/t/enhancing-user-experience-implementing-guided-tutorial-functionality-with-driver-js/7587

**Comment by dongrentianyu** [comment]
但怎么找到你写的插件呢？

感觉你有很多插件已经实现了我们想做的，但都没有添加到cpl，这是为什么呢？

**Comment by linonetwo** [comment]
我觉得这个适合加到 tiddlywiki XP 里，搞一个从零到一的教程

引导步骤可以做成插件吗？然后往 XP 里一装，然后发布为新的教程 HTML。这样就不会影响到 XP 作者了。就是这个插件+具体引导内容的插件，两个插件往里一装。

**Comment by dongrentianyu** [comment]
确实是这样的想法。但现在进展全无。啥也不会。
